### PR TITLE
Only events

### PR DESCRIPTION
**Pull request by kristenmills**
We should make this official.

### CODE REVIEW

**Comment by weswigham** [comment]
Question: The orbiter content editor js is still here, and the model for it is still here - just the route, controller, and template were removed. Is this something we want to retain or not? If we want to remove it, there's pretty much an entire asserts/javascripts folder we could remove (and a bit of the model).

**Comment by kristenmills** [comment]
I don't think I completely removed everything due to the fact that I don't know WTF very well. I only removed what I was sure wasn't relevant. Since you know it better than I do, do you want to just do another look through and delete anything you think is unnecessary?  That would be helpful.

**Comment by weswigham** [comment]
I guess it's time for a grand culling, then.

**Comment by weswigham** [comment]
I branched off of only-events with a [mass culling.](https://github.com/rit-sse/wtf/tree/culling)

From what I know everything I removed should be fine to delete. I killed all the templates for pages I was relatively sure were no longer used in this repo, removed all the js dependencies we were no longer using, removed the out of date docs/prototypes folder, I removed all the empty auto-generated folders, and I hoped all of the hopelessly out of date rspec/cucumber-related files. I also removed fog (the unused amazon s3), but left in carrierwave... out image upload helper seems to depend on it. (Now, if we don't actually use that, we can rip out that, too. I was unsure.)

Note: I haven't actually fully tested this yet - these are just all the things I'm pretty confident we should be able to just rip out. (I am unsure what simply deleting a model does, it probably requires a new migration)

**Pull request closed without merging**
