### PR TITLE
Featured events

### PR DESCRIPTION
**Pull request by derekerdmann**
Add ability to mark events as "featured," which places them in special boxes on the events page. Featured events are required to have short descriptions and images.

The GTV or FTV views could use the featured flag on an event to determine if it belongs in the slideshow, but that isn't implemented in this pull request.

### CODE REVIEW

**Comment by 7imbrook** [comment]
Thoughts on adding the GTV and FTV support in this pull?

**Comment by derekerdmann** [comment]
Yeah, I guess so. The only event in there now is RapDev, so it wouldn't be breaking any existing GTV views.

**Comment by derekerdmann** [comment]
GTV support is in. Turned out most of the client-side stuff was already there, and all it took was another filter in the events query in the controller.

**Comment by 7imbrook** [comment]
Thanks @derekerdmann

**Pull request merged**
