### PR TITLE
Add/Modify Index Page Header Slides

### PR DESCRIPTION
**Pull request by weswigham**
Just wanted to let you know I'm actually working on things.

It'd be nice if I could get some feedback on it, and some advice on how to actually use the test suite. o.O

Anyways, log into the admin account on the homepage and you'll see some fancy new buttons; they do stuff.

I was originally planning on making the header a markdown block; but that doesn't allow for the kind of formatting control that you'd like to have in the header. 

Oh, we're also using a newer version of the bootstrap javascript (yay) since the old version had a bug in carousel that was crippling me, and in addition, we no longer use the "Orbit" plugin (we use the bootstrap carousel instead) since that had even MORE crippling bugs when you tried to control it with javascript, and besides, we were using bootstrap already anyways, why use another plugin just for the carousel when bootstrap already comes with one? (Note: still need to remove Orbit from the repo.)

So, main feature right now is that the main page header is now editable by admins, loads content from the db, and has fancy live-previewing. We should try to get live-previewing into all of our edit dialogs; they really make it easier to put a page together.

### CODE REVIEW

**Comment by weswigham** [comment]
I've also done some work on issue #39 now.

**Comment by ghost** [comment]
Cool.  I took a quick look over things and tested it out.  The live editing stuff is pretty cool.  Eventually I think we could move it to use the blocks / sections stuff from the pages branch since they support different pre-coded layouts  which may be easier for people who don't want to mess with html/css.

With the bootstrap carousel, it would be nice to get some of the features we had with orbit added back (like animations between headers, and hiding the arrows unless moused over the area).  A couple of useful features I can also think of include being able to change the order that headers appear in, and some sort of dialog to quickly upload images so they can be included in the html.

I just realized I didn't try out the event highlight stuff, I'll give that a look soon ^^;

As for the testing we are doing, unfortunately this is an area I am not familiar with at all in our rails setup and something I've been meaning to look into for a long time.  If you figure out what frameworks we are using / what tests should look like before I get a chance, let me know.

**Comment by ghost** [comment]
The event highlight looks good too.  Todd will be very happy :)  I'm going to try and make a push this next week to get all of this (and the pages branch) merged to master soon.  Testing is still an issue though, we'll need to make sure there are at least no glaring issues.

**Comment by weswigham** [comment]
On the subject of  "Eventually I think we could move it to use the blocks / sections stuff from the pages branch since they support different pre-coded layouts which may be easier for people who don't want to mess with html/css," I've started some work on adding some previews to the markdown you put into those blocks. The hardest part is syncing up the options on our serverside and clientside markdown parsers when doing this.... actually, sitting here staring at github, maybe I should hide the preview in a tab like github does for comments? Because with the ammount of content a block can have the live preview gets really cluttered really fast.

I've left the header editor as html as, though I could easily drop in markdown, the headers either need some preset forms (picture left, header and paragraph right; reversed; full picture, etc) or you really need the raw html to get the kind of styling control you want over the header. As for image uploading, I think something like how github has the ability to let you drag imaged into the comment box would be sweet, so I'll look into that.

**Comment by ghost** [comment]
Yeah, just having a preview tab would be plenty fine.  The live preview stuff is cool, but it may be too much effort to make all blocks behave this way.  Having one 'preview' button/tab for the entire page would probably be best in the long term.

**Pull request merged**
